sudo: required
language: generic
service:
  - docker
before_install:
  - docker build -t yukairex/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true yukairex/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-235633645258'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
